//////////////////////////////////////////////////////////////////////////////
//
// This file is part of sc4-legalize-gambling-ordinance-upgrade, a DLL Plugin
// for SimCity 4 that updates the built-in ordinance to have its income based
// on the city's residential population.
//
// Copyright (c) 2023 Nicholas Hayes
//
// This file is licensed under terms of the MIT License.
// See LICENSE.txt for more information.
//
//////////////////////////////////////////////////////////////////////////////

#pragma once
#include "cISC4Ordinance.h"
#include "cIGZSerializable.h"
#include "cRZBaseString.h"
#include "OrdinancePropertyHolder.h"
#include "Logger.h"
#include "SC4Percentage.h"
#include "StringResourceKey.h"

// Specifies the group and instance IDs of the built-in ordinance's
// Exemplar. This information is written to the save game ordinance subfile.
// The instance ID is also the ordinance's unique ID.
struct BuiltInOrdinanaceExemplarInfo
{
	uint32_t group;
	uint32_t instance;
};

class cISC4City;
class cISC4ResidentialSimulator;
class cISC4Simulator;

// A base class for overriding SC4's built-in ordinances.
// The class uses the same ordinance save data format as SC4.
class SC4BuiltInOrdinanceBase : public cISC4Ordinance, private cIGZSerializable
{
public:

	/**
	 * @brief Constructs an instance of the class.
	 * @param info The group and instance ID of the ordinance exemplar.
	 * @param name The name of the ordinance.
	 * @param nameKey The key that identifies the LTEXT resource containing the localized name.
	 * @param description The ordinance description.
	 * @param descriptionKey The key that identifies the LTEXT resource containing the localized description.
	 * @param yearFirstAvailable The in-game year required for the ordinance to become available, starting from 2000.
	 * @param monthlyChance The chance each month that the ordinance will become available. Unused in SC4.
	 * @param enactmentIncome Income generated by enacting the ordinance.
	 * @param retracmentIncome Cost of retracting the ordinance.
	 * @param monthlyConstantIncome The monthly constant income/expense.
	 * @param monthlyIncomeFactor The factor applied to the monthly cost.
	 * @param advisorID The advisor associated with this ordinance. Unused in SC4.
	 * @param isIncomeOrdinance True if the ordinance generates income; otherwise, false.
	 * @param properties A list of in-game effects that the ordinance has.
	*/
	SC4BuiltInOrdinanceBase(
		BuiltInOrdinanaceExemplarInfo info,
		const char* name,
		const StringResourceKey& nameKey,
		const char* description,
		const StringResourceKey& descriptionKey,
		uint32_t yearFirstAvailable,
		const SC4Percentage& monthlyChance,
		int64_t enactmentIncome,
		int64_t retracmentIncome,
		int64_t monthlyConstantIncome,
		float monthlyIncomeFactor,
		uint32_t advisorID,
		bool isIncomeOrdinance,
		const OrdinancePropertyHolder& properties);

	SC4BuiltInOrdinanceBase(const SC4BuiltInOrdinanceBase& other);
	SC4BuiltInOrdinanceBase(SC4BuiltInOrdinanceBase&& other) noexcept;

	SC4BuiltInOrdinanceBase& operator=(const SC4BuiltInOrdinanceBase& other);
	SC4BuiltInOrdinanceBase& operator=(SC4BuiltInOrdinanceBase&& other) noexcept;

	bool QueryInterface(uint32_t riid, void** ppvObj) final;

	uint32_t AddRef() final;

	uint32_t Release() final;

	bool Init(void) final;

	bool Shutdown(void) final;

	/**
	 * @brief Gets the monthly income/expense for this ordinance.
	 * @return The monthly income/expense for this ordinance.
	 * @remarks This method uses a default algorithm of
	 * <monthly constent income> + (<city population> x <monthly income factor>).
	 * This method can be overridden to use a custom algorithm.
	*/
	virtual int64_t GetCurrentMonthlyIncome(void);

	/**
	 * @brief Gets the unique ordinance ID.
	 * @return The unique ordinance ID.
	*/
	uint32_t GetID(void) const final;

	/**
	 * @brief Gets the ordinance name.
	 * @return The ordinance name.
	*/
	cIGZString* GetName(void) final;

	/**
	 * @brief Gets the ordinance description.
	 * @return The ordinance description.
	*/
	cIGZString* GetDescription(void) final;

	/**
	 * @brief Gets the in-game year that the ordinance becomes available.
	 * @return The in-game year that the ordinance becomes available.
	 *
	 * @remarks By default the ordinances will be available at the start of the game.
	 * This method can be overridden to set a custom start year.
	 * Note that in SimCity 4 the in-game date starts in the year 2000.
	*/
	virtual uint32_t GetYearFirstAvailable(void) final;

	/**
	 * @brief The chance that the ordinance will become available each month.
	 * This feature is not implemented.
	 *
	 * @return The chance that the ordinance will become available each month.
	*/
	virtual SC4Percentage GetChanceAvailability(void) final;

	/**
	 * @brief Gets the revenue generated by enacting this ordinance.
	 * @return The revenue generated by enacting this ordinance.
	*/
	int64_t GetEnactmentIncome(void) final;

	/**
	 * @brief Gets the cost of retracting this ordinance.
	 * @return The cost of retracting this ordinance.
	*/
	int64_t GetRetracmentIncome(void) final;

	/**
	 * @brief Gets the monthly constant income/expense value for the ordinance.
	 * @return The monthly constant income/expense value for the ordinance.
	*/
	int64_t GetMonthlyConstantIncome(void) final;

	/**
	 * @brief Gets the factor applied to the ordinance cost.
	 * @return The factor applied to the ordinance cost.
	*/
	float GetMonthlyIncomeFactor(void) final;

	/**
	 * @brief Gets a collection of the ordinance properties/effects.
	 * @return The ordinance properties/effects.
	*/
	cISCPropertyHolder* GetMiscProperties() final;

	/**
	 * @brief Gets a value that identifies the in-game advisor related to this
	 * ordinance. This is unused in SimCity 4 and always returns zero.
	 * @return Zero.
	*/
	uint32_t GetAdvisorID(void) final;

	bool IsAvailable(void);

	bool IsOn(void);

	bool IsEnabled(void);

	/**
	 * @brief Gets the monthly adjusted income.
	 * @return The monthly adjusted income.
	*/
	virtual int64_t GetMonthlyAdjustedIncome(void);

	/**
	 * @brief Defines the conditions that are required for the ordinance to become available.
	 * @return True if the ordinance should become available in the menu; otherwise, false.
	 * @remarks By default the only required condition is the starting year @see GetYearFirstAvailable.
	 * This method can be overridden to provide custom conditions for the ordinance availability.
	*/
	virtual bool CheckConditions(void);

	/**
	 * @brief Gets a value indicating whether this ordinance generates income.
	 * @return True if this ordinance generates income; otherwise, false.
	*/
	bool IsIncomeOrdinance(void) final;

	/**
	 * @brief This is called during the monthly ordinance simulation.
	 * @return True if successful; otherwise, false.
	*/
	virtual bool Simulate(void);

	bool SetAvailable(bool isAvailable);

	bool SetOn(bool isOn);

	bool SetEnabled(bool isEnabled);

	bool ForceAvailable(bool isAvailable);

	bool ForceOn(bool isOn);

	bool ForceEnabled(bool isEnabled);

	bool ForceMonthlyAdjustedIncome(int64_t monthlyAdjustedIncome) final;


protected:

	virtual void InitializeOrdinanceComponents(cISC4City* pCity);

	virtual void ShutdownOrdinanceComponents(cISC4City* pCity);

	Logger& logger;

	OrdinancePropertyHolder miscProperties;

private:

	static bool ReadBool(cIGZIStream& stream, bool& value);
	static bool WriteBool(cIGZOStream& stream, bool value);

	// The Write and Read methods are used to persist the required
	// values to the save game. The methods are marked as final to
	// prevent them from being overridden in derived classes. All
	// of the built-in ordinances use the same layout for the save
	// game serialization.

	bool Write(cIGZOStream& stream) final;
	bool Read(cIGZIStream& stream) final;
	uint32_t GetGZCLSID() final;

	void LoadLocalizedStringResources();

	// The following values are persisted the save game:

	bool initialized;
	uint32_t clsid;
	cRZBaseString name;
	cRZBaseString description;
	uint32_t yearFirstAvailable;
	SC4Percentage monthlyChance;
	int64_t enactmentIncome;
	int64_t retracmentIncome;
	int64_t monthlyConstantIncome;
	int64_t monthlyAdjustedIncome;
	float monthlyIncomeFactor;
	uint32_t advisorID;
	bool isIncomeOrdinance;
	bool available;
	bool on;
	bool enabled;
	// End of save game values

	uint32_t refCount;
	BuiltInOrdinanaceExemplarInfo exemplarInfo;
	StringResourceKey nameKey;
	StringResourceKey descriptionKey;
	cISC4ResidentialSimulator* pResidentialSimulator;
	cISC4Simulator* pSimulator;
	bool haveDeserialized;
};

